# 📁 stack.yml (sin base de datos local)
version: '3.8'

services:
  gateway:
    build: ./gateway_api
    ports:
      - "8083:8083"
    depends_on:
      - cliente_service
      - pedido_service

  cliente_service:
    build: ./services/cliente_service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  pedido_service:
    build: ./services/pedido_service
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=${DATABASE_URL}
